In [7]:
import numpy as np
from numpy import genfromtxt
from sklearn.model_selection import train_test_split


# from sklearn.model_selection import _split
data = genfromtxt('bank_note_data.csv', delimiter=',')

# print(data)

labels = data[1:, 4]
features = data[1:, 0:4]

X = features
y = labels
# split to train and test sets
# X y
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

scaler.fit(X_train)
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

# print(scaled_X_train.max())
print(features)


[[  3.6216    8.6661   -2.8073   -0.44699]
 [  4.5459    8.1674   -2.4586   -1.4621 ]
 [  3.866    -2.6383    1.9242    0.10645]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771 ]
 [ -3.5637   -8.3827   12.393    -1.2823 ]
 [ -2.5419   -0.65804   2.6842    1.1952 ]]


In [10]:

from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(4, input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

Instructions for updating:
Colocations handled automatically by placer.


In [11]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)


Instructions for updating:
Use tf.cast instead.
Epoch 1/50
 - 1s - loss: 0.6790 - accuracy: 0.5552
Epoch 2/50
 - 0s - loss: 0.6714 - accuracy: 0.5552
Epoch 3/50
 - 0s - loss: 0.6649 - accuracy: 0.5552
Epoch 4/50
 - 0s - loss: 0.6585 - accuracy: 0.5552
Epoch 5/50
 - 0s - loss: 0.6510 - accuracy: 0.5552
Epoch 6/50
 - 0s - loss: 0.6434 - accuracy: 0.5552
Epoch 7/50
 - 0s - loss: 0.6348 - accuracy: 0.5552
Epoch 8/50
 - 0s - loss: 0.6256 - accuracy: 0.6031
Epoch 9/50
 - 0s - loss: 0.6152 - accuracy: 0.6677
Epoch 10/50
 - 0s - loss: 0.6039 - accuracy: 0.6927
Epoch 11/50
 - 0s - loss: 0.5918 - accuracy: 0.7167
Epoch 12/50
 - 0s - loss: 0.5784 - accuracy: 0.7521
Epoch 13/50
 - 0s - loss: 0.5641 - accuracy: 0.7781
Epoch 14/50
 - 0s - loss: 0.5489 - accuracy: 0.7979
Epoch 15/50
 - 0s - loss: 0.5317 - accuracy: 0.8062
Epoch 16/50
 - 0s - loss: 0.5141 - accuracy: 0.8156
Epoch 17/50
 - 0s - loss: 0.4963 - accuracy: 0.8146
Epoch 18/50
 - 0s - loss: 0.4779 - accuracy: 0.8188
Epoch 19/50
 - 0s - loss:

In [12]:
model.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    

In [13]:
from sklearn.metrics import confusion_matrix, classification_report
predictions = model.predict_classes(scaled_X_test)
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.95      1.00      0.97       229
         1.0       0.99      0.93      0.96       183

    accuracy                           0.97       412
   macro avg       0.97      0.97      0.97       412
weighted avg       0.97      0.97      0.97       412



In [17]:
model.save('kerasbanknote.h5')

In [21]:
from keras.models import load_model